fo = open("test1.dxf","w")
fo.write("0\n")
fo.write("SECTION\n")
fo.write("2\n")
fo.write("ENTITIES\n")

fo.write("0\n")
fo.write("TEXT\n")
fo.write("1\n")
fo.write("I Love you Anurak Srangpol\n")
fo.write("10\n")
fo.write("10\n")
fo.write("20\n")
fo.write("10\n")


fo.write("2\n")
fo.write("ENTITIES\n")

# draw line
fo.write("0\n")
fo.write("LINE\n")
fo.write("8\n")       
fo.write("0\n")       
fo.write("10\n")
fo.write("0\n")
fo.write("20\n")
fo.write("0\n")
fo.write("11\n")
fo.write("200\n")
fo.write("21\n")
fo.write("0\n")

fo.write("0\n")
fo.write("LINE\n")
fo.write("8\n")       
fo.write("0\n")       
fo.write("10\n")
fo.write("0\n")
fo.write("20\n")
fo.write("30\n")
fo.write("11\n")
fo.write("200\n")
fo.write("21\n")
fo.write("30\n")

fo.write("0\n")
fo.write("LINE\n")
fo.write("8\n")       
fo.write("0\n")       
fo.write("10\n")
fo.write("0\n")
fo.write("20\n")
fo.write("0\n")
fo.write("11\n")
fo.write("0\n")
fo.write("21\n")
fo.write("30\n")

fo.write("0\n")
fo.write("LINE\n")
fo.write("8\n")       
fo.write("0\n")       
fo.write("10\n")
fo.write("200\n")
fo.write("20\n")
fo.write("0\n")
fo.write("11\n")
fo.write("200\n")
fo.write("21\n")
fo.write("30\n")


fo.write("0\n")
fo.write("ENDSEC\n")
fo.close()
